# Generated by Django 5.0 on 2025-11-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiver',
            new_name='to_user',
        ),
    ]
