# Generated by Django 5.0 on 2025-11-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_cameraman',
            field=models.BooleanField(default=False),
        ),
    ]
