# Generated by Django 5.1.7 on 2026-03-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_cameraman'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_given_review',
            field=models.BooleanField(default=False),
        ),
    ]
