# Generated by Django 5.1.7 on 2026-03-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_has_given_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_given_review',
        ),
    ]
