# Generated by Django 5.0 on 2026-02-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_mention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
